# Generated by Django 5.1.4 on 2025-01-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppprog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarydynamicsofyear',
            options={'verbose_name': 'Динамика уровня зарплат по годам', 'verbose_name_plural': 'Динамика уровня зарплат по годам'},
        ),
        migrations.AlterField(
            model_name='salarydynamicsofyear',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Зарплата в рублях'),
        ),
    ]
