# Generated by Django 5.1.4 on 2025-01-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppprog', '0002_alter_salarydynamicsofyear_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountDynamicsOfYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('vacancies_number', models.PositiveIntegerField(verbose_name='Вакансий')),
            ],
            options={
                'verbose_name': 'Динамика количества вакансий по годам',
                'verbose_name_plural': 'Динамика количества вакансий по годам',
            },
        ),
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название изображения')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='RateOfCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('rate', models.FloatField(verbose_name='Зарплата в рублях')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доля вакансий по городам',
            },
        ),
        migrations.CreateModel(
            name='SalaryDynamicsOfCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата в рублях')),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам',
                'verbose_name_plural': 'Уровень зарплат по городам',
            },
        ),
        migrations.CreateModel(
            name='Top20Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=255, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'ТОП-20 навыков по годам',
                'verbose_name_plural': 'ТОП-20 навыков по годам',
            },
        ),
    ]
