# Generated by Django 5.1.4 on 2025-01-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppprog', '0003_countdynamicsofyear_imagesmodel_rateofcity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyCountDynamicsOfYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('vacancies_number', models.PositiveIntegerField(verbose_name='Вакансий')),
            ],
            options={
                'verbose_name': 'Динамика количества вакансий по годам для профессии C++ программист',
                'verbose_name_plural': 'Динамика количества вакансий по годам для профессии C++ программист',
            },
        ),
        migrations.CreateModel(
            name='VacancySalaryDynamicsOfYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата в рублях')),
            ],
            options={
                'verbose_name': 'Динамика уровня зарплат по годам для профессии C++ программист',
                'verbose_name_plural': 'Динамика уровня зарплат по годам для профессии C++ программист',
            },
        ),
        migrations.AlterField(
            model_name='rateofcity',
            name='rate',
            field=models.FloatField(verbose_name='Доля'),
        ),
    ]
