# Generated by Django 5.1.4 on 2025-01-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppprog', '0004_vacancycountdynamicsofyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyRateOfCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('rate', models.FloatField(verbose_name='Доля')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам для профессии C++ программист',
                'verbose_name_plural': 'Доля вакансий по городам для профессии C++ программист',
            },
        ),
        migrations.CreateModel(
            name='VacancySalaryDynamicsOfCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата в рублях')),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам для профессии C++ программист',
                'verbose_name_plural': 'Уровень зарплат по городам для профессии C++ программист',
            },
        ),
    ]
