# Generated by Django 5.1.4 on 2025-01-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cppprog', '0005_vacancyrateofcity_vacancysalarydynamicsofcity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rateofcity',
            options={'ordering': ['-rate'], 'verbose_name': 'Доля вакансий по городам', 'verbose_name_plural': 'Доля вакансий по городам'},
        ),
        migrations.AlterModelOptions(
            name='salarydynamicsofcity',
            options={'ordering': ['-salary'], 'verbose_name': 'Уровень зарплат по городам', 'verbose_name_plural': 'Уровень зарплат по городам'},
        ),
        migrations.AlterModelOptions(
            name='vacancyrateofcity',
            options={'ordering': ['-rate'], 'verbose_name': 'Доля вакансий по городам для профессии C++ программист', 'verbose_name_plural': 'Доля вакансий по городам для профессии C++ программист'},
        ),
        migrations.AlterModelOptions(
            name='vacancysalarydynamicsofcity',
            options={'ordering': ['-salary'], 'verbose_name': 'Уровень зарплат по городам для профессии C++ программист', 'verbose_name_plural': 'Уровень зарплат по городам для профессии C++ программист'},
        ),
    ]
