# Generated by Django 5.1.4 on 2025-01-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppprog', '0006_alter_rateofcity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top20SkillsYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Года для ТОП-20 навыков',
                'verbose_name_plural': 'Года для ТОП-20 навыков',
            },
        ),
        migrations.AddField(
            model_name='top20skills',
            name='count',
            field=models.PositiveIntegerField(default=2025, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='top20skills',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cppprog.top20skillsyears'),
        ),
    ]
