# Generated by Django 5.1.4 on 2025-01-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppprog', '0007_top20skillsyears_top20skills_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top20skills',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterModelOptions(
            name='countdynamicsofyear',
            options={'ordering': ['vacancies_number'], 'verbose_name': 'Динамика количества вакансий по годам', 'verbose_name_plural': 'Динамика количества вакансий по годам'},
        ),
        migrations.AlterModelOptions(
            name='imagesmodel',
            options={'ordering': ['-name'], 'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='salarydynamicsofyear',
            options={'ordering': ['salary'], 'verbose_name': 'Динамика уровня зарплат по годам', 'verbose_name_plural': 'Динамика уровня зарплат по годам'},
        ),
        migrations.AlterModelOptions(
            name='top20skills',
            options={'ordering': ['-count'], 'verbose_name': 'ТОП-20 навыков по годам', 'verbose_name_plural': 'ТОП-20 навыков по годам'},
        ),
        migrations.AlterModelOptions(
            name='vacancycountdynamicsofyear',
            options={'ordering': ['vacancies_number'], 'verbose_name': 'Динамика количества вакансий по годам для профессии C++ программист', 'verbose_name_plural': 'Динамика количества вакансий по годам для профессии C++ программист'},
        ),
        migrations.AlterModelOptions(
            name='vacancysalarydynamicsofyear',
            options={'ordering': ['salary'], 'verbose_name': 'Динамика уровня зарплат по годам для профессии C++ программист', 'verbose_name_plural': 'Динамика уровня зарплат по годам для профессии C++ программист'},
        ),
        migrations.DeleteModel(
            name='Top20SkillsYears',
        ),
    ]
