# Generated by Django 5.1.4 on 2025-01-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cppprog', '0008_alter_top20skills_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top20skills',
            options={'ordering': ['-year', '-count'], 'verbose_name': 'ТОП-20 навыков по годам', 'verbose_name_plural': 'ТОП-20 навыков по годам'},
        ),
    ]
