# Generated by Django 5.1.4 on 2025-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppprog', '0009_alter_top20skills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyTop20Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=255, verbose_name='Навык')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'ТОП-20 навыков по годам для профессии C++ программист',
                'verbose_name_plural': 'ТОП-20 навыков по годам для профессии C++ программист',
                'ordering': ['-year', '-count'],
            },
        ),
    ]
